AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  TAPILocal

  Sample SAM Template for TradeAPILocal

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  TapiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: api/
      Handler: uk.gov.dvsa.mot.app.LambdaHandler::handleRequest
      Runtime: java8
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SEARCH_API_URL:
          SEARCH_API_KEY:
          SEARCH_API_CONNECTION_TIMEOUT:
          DATABASE_USERNAME:
          DATABASE_CONNECTION:
          DATABASE_PASSWORD:
          OBFUSCATION_SECRET:
          ANNUAL_TESTS_MAX_QUERYABLE_REGISTRATIONS:
          LOG_LEVEL:
          APP_ENV:
      Events:
        motTests:
          Type: Api
          Properties:
            Path: /trade/vehicles/mot-tests
            Method: GET
        AnnualTests:
          Type: Api
          Properties:
            Path: /trade/vehicles/annual-tests
            Method: GET
        MotrSearch:
          Type: Api
          Properties:
            Path: /motr/v2/search/registration/{registration}
            Method: GET
        MotrSearchCommerical:
          Type: Api
          Properties:
            Path: /motr/v2/search/commercial/registration/{registration}
            Method: GET
        MotrSearchDvlaId:
          Type: Api
          Properties:
            Path: /motr/v2/search/dvla-id/{id}
            Method: GET
        MotrSearchMotTestNumber:
          Type: Api
          Properties:
            Path: /motr/v2/search/mot-test/{motTestNumber}
            Method: GET
        MothRegAndMake:
          Type: Api
          Properties:
            Path: /mot-history/{registration}/{make}
            Method: GET
