//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.09 at 08:46:59 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dvsa.gov.uk/mot/vehicle/api", elementFormDefault = javax.xml.bind.annotation
        .XmlNsForm.QUALIFIED)
package uk.gov.dvsa.mot.vehicle.api;
