package uk.gov.dvsa.mot.persist.jdbc;

/**
 * SQL queries for the MotTestReadDaoJdbc class to use
 */
@SuppressWarnings({"checkstyle:OperatorWrap", "checkstyle:Indentation"})
class MotTestReadSql {
    //Horrible optimised query to get the mot test history records
    static final String QueryGetMotHistoryCurrentByDateRange =
            "SELECT `vehicle`.`id` "
                    + ", `mot_test`.`id` "
                    + ", `rfrmap`.`id` "
                    + ", `vehicle`.`registration` "
                    + ", `make`.`name` AS `make_name` "
                    + ", `model`.`name` AS `model_name` "
                    + ", `vehicle`.`first_used_date` "
                    + ", `fuel_type`.`name` AS `fuel_type` "
                    + ", `colour1`.`name` AS `primary_colour` "
                    + ", `colour2`.`name` AS `secondary_colour` "
                    + ", `mot_test`.`started_date` "
                    + ", `mot_test`.`completed_date` "
                    + ", `mot_test_status`.`name` AS `test_result` "
                    + ", `mot_test`.`expiry_date` "
                    + ", `mot_test`.`odometer_value` "
                    + ", `mot_test`.`odometer_unit` "
                    + ", `mot_test`.`odometer_result_type` "
                    + ", `mot_test`.`number` AS `mot_test_number` "
                    + ", `rfr_type`.`name` `rfr_type` "
                    + ", TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(COALESCE(`location`.`lateral`, ''),' ', "
                    + "  COALESCE(`location`.`longitudinal`, ''))), ' ', "
                    + "  COALESCE(`location`.`vertical`, ''))), ' ', "
                    + "  COALESCE(`timap`.`description`, ''))),' ', "
                    + "  CASE WHEN `rfr_type`.`name` = 'ADVISORY' "
                    + "  THEN    COALESCE(`rfrl`.`advisory_text`, '') "
                    + "  ELSE    COALESCE(`rfrl`.`name`, '') "
                    + "  END)),' ',' ', "
                    + "  COALESCE(`rfrmap_comment`.`comment`, ''))), "
                    + "  CASE "
                    + "  WHEN `rfr`.`inspection_manual_reference` IS NOT NULL THEN "
                    + "  CONCAT(' (', `rfr`.`inspection_manual_reference`, ')') ELSE ' ' END)) `rfr_and_comments` "
                    + "FROM    `mot2`.`mot_test_current` AS `mot_test` "
                    + "LEFT JOIN `mot2`.`mot_test_current_rfr_map` AS `rfrmap` ON `rfrmap`.`mot_test_id` = `mot_test`.`id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_location_type` AS `location` ON `location`.`id` = `rfrmap`" +
                    ".`mot_test_rfr_location_type_id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_map_comment` AS `rfrmap_comment` ON `rfrmap_comment`.`id` = `rfrmap`.`id` "
                    + "LEFT JOIN `mot2`.`reason_for_rejection_type` AS `rfr_type` ON `rfr_type`.`id` = `rfrmap`.`rfr_type_id` "
                    + "LEFT JOIN `mot2`.`language_type` AS `l` ON `l`.`code` = 'EN' "
                    + "LEFT JOIN `mot2`.`reason_for_rejection` AS `rfr` ON `rfrmap`.`rfr_id` = `rfr`.`id` "
                    + "LEFT JOIN `mot2`.`rfr_language_content_map` AS `rfrl` ON `rfrl`.`rfr_id` = `rfr`.`id` AND `rfrl`" +
                    ".`language_type_id` = `l`.`id` "
                    + "LEFT JOIN `mot2`.`test_item_category` AS `ti` ON `rfr`.`test_item_category_id` = `ti`.`id` "
                    + "LEFT JOIN `mot2`.`ti_category_language_content_map` AS `timap` ON `timap`.`test_item_category_id` = `rfr`" +
                    ".`test_item_category_id` AND `timap`.`language_lookup_id` = `l`.`id` "
                    + "JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "JOIN "
                    + "( SELECT  `mot_test`.`vehicle_id` "
                    + "  FROM    `mot2`.`mot_test_current` as `mot_test` "
                    + "  JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "  JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "  WHERE   `mot_test`.`submitted_date` >= ? "
                    + "  AND     `mot_test`.`submitted_date` < ? "
                    + "  AND     `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "  AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + ") as `vehicles` on `vehicles`.`vehicle_id` = `mot_test`.`vehicle_id` "
                    + "WHERE   `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + "ORDER BY `mot_test`.`vehicle_id`, `mot_test`.`id`, `mot_test`.`completed_date` DESC ";

    //Horrible optimised query to get the mot test history records
    static final String QueryGetMotHistoryHistoryByDateRange =
            "SELECT `vehicle`.`id` "
                    + ", `mot_test`.`id` "
                    + ", `rfrmap`.`id` "
                    + ", `vehicle`.`registration` "
                    + ", `make`.`name` AS `make_name` "
                    + ", `model`.`name` AS `model_name` "
                    + ", `vehicle`.`first_used_date` "
                    + ", `fuel_type`.`name` AS `fuel_type` "
                    + ", `colour1`.`name` AS `primary_colour` "
                    + ", `colour2`.`name` AS `secondary_colour` "
                    + ", `mot_test`.`started_date` "
                    + ", `mot_test`.`completed_date` "
                    + ", `mot_test_status`.`name` AS `test_result` "
                    + ", `mot_test`.`expiry_date` "
                    + ", `mot_test`.`odometer_value` "
                    + ", `mot_test`.`odometer_unit` "
                    + ", `mot_test`.`odometer_result_type` "
                    + ", `mot_test`.`number` AS `mot_test_number` "
                    + ", `rfr_type`.`name` `rfr_type` "
                    + ", TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(COALESCE(`location`.`lateral`, ''),' ', "
                    + "  COALESCE(`location`.`longitudinal`, ''))), ' ', "
                    + "  COALESCE(`location`.`vertical`, ''))), ' ', "
                    + "  COALESCE(`timap`.`description`, ''))),' ', "
                    + "  CASE WHEN `rfr_type`.`name` = 'ADVISORY' "
                    + "  THEN    COALESCE(`rfrl`.`advisory_text`, '') "
                    + "  ELSE    COALESCE(`rfrl`.`name`, '') "
                    + "  END)),' ',' ', "
                    + "  COALESCE(`rfrmap_comment`.`comment`, ''))), "
                    + "  CASE "
                    + "  WHEN `rfr`.`inspection_manual_reference` IS NOT NULL THEN "
                    + "  CONCAT(' (', `rfr`.`inspection_manual_reference`, ')') ELSE ' ' END)) `rfr_and_comments` "
                    + "FROM    `mot2`.`mot_test_history` AS `mot_test` "
                    + "LEFT JOIN `mot2`.`mot_test_history_rfr_map` AS `rfrmap` ON `rfrmap`.`mot_test_id` = `mot_test`.`id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_location_type` AS `location` ON `location`.`id` = `rfrmap`" +
                    ".`mot_test_rfr_location_type_id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_map_comment` AS `rfrmap_comment` ON `rfrmap_comment`.`id` = `rfrmap`.`id` "
                    + "LEFT JOIN `mot2`.`reason_for_rejection_type` AS `rfr_type` ON `rfr_type`.`id` = `rfrmap`.`rfr_type_id` "
                    + "LEFT JOIN `mot2`.`language_type` AS `l` ON `l`.`code` = 'EN' "
                    + "LEFT JOIN `mot2`.`reason_for_rejection` AS `rfr` ON `rfrmap`.`rfr_id` = `rfr`.`id` "
                    + "LEFT JOIN `mot2`.`rfr_language_content_map` AS `rfrl` ON `rfrl`.`rfr_id` = `rfr`.`id` AND `rfrl`" +
                    ".`language_type_id` = `l`.`id` "
                    + "LEFT JOIN `mot2`.`test_item_category` AS `ti` ON `rfr`.`test_item_category_id` = `ti`.`id` "
                    + "LEFT JOIN `mot2`.`ti_category_language_content_map` AS `timap` ON `timap`.`test_item_category_id` = `rfr`" +
                    ".`test_item_category_id` AND `timap`.`language_lookup_id` = `l`.`id` "
                    + "JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "JOIN "
                    + "( SELECT  `mot_test`.`vehicle_id` "
                    + "  FROM    `mot2`.`mot_test_current` as `mot_test` "
                    + "  JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "  JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "  WHERE   `mot_test`.`submitted_date` >= ? "
                    + "  AND     `mot_test`.`submitted_date` < ? "
                    + "  AND     `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "  AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + ") as `vehicles` on `vehicles`.`vehicle_id` = `mot_test`.`vehicle_id` "
                    + "WHERE   `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + "ORDER BY `mot_test`.`vehicle_id`, `mot_test`.`id`, `mot_test`.`completed_date` DESC ";

    //Horrible optimised query that breaks the mot_test / vehicle service division
    static final String QueryGetMotHistoryCurrentVehicleByDateRange =
            "SELECT `vehicle`.`id` "
                    + ", `mot_test`.`id` "
                    + ", `rfrmap`.`id` "
                    + ", `vehicle`.`registration` "
                    + ", `make`.`name` AS `make_name` "
                    + ", `model`.`name` AS `model_name` "
                    + ", `vehicle`.`first_used_date` "
                    + ", `fuel_type`.`name` AS `fuel_type` "
                    + ", `colour1`.`name` AS `primary_colour` "
                    + ", `colour2`.`name` AS `secondary_colour` "
                    + ", `mot_test`.`started_date` "
                    + ", `mot_test`.`completed_date` "
                    + ", `mot_test_status`.`name` AS `test_result` "
                    + ", `mot_test`.`expiry_date` "
                    + ", `mot_test`.`odometer_value` "
                    + ", `mot_test`.`odometer_unit` "
                    + ", `mot_test`.`odometer_result_type` "
                    + ", `mot_test`.`number` AS `mot_test_number` "
                    + ", `rfr_type`.`name` `rfr_type` "
                    + ", TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(COALESCE(`location`.`lateral`, ''),' ', "
                    + "  COALESCE(`location`.`longitudinal`, ''))), ' ', "
                    + "  COALESCE(`location`.`vertical`, ''))), ' ', "
                    + "  COALESCE(`timap`.`description`, ''))),' ', "
                    + "  CASE WHEN `rfr_type`.`name` = 'ADVISORY' "
                    + "  THEN    COALESCE(`rfrl`.`advisory_text`, '') "
                    + "  ELSE    COALESCE(`rfrl`.`name`, '') "
                    + "  END)),' ',' ', "
                    + "  COALESCE(`rfrmap_comment`.`comment`, ''))), "
                    + "  CASE "
                    + "  WHEN `rfr`.`inspection_manual_reference` IS NOT NULL THEN "
                    + "  CONCAT(' (', `rfr`.`inspection_manual_reference`, ')') ELSE ' ' END)) `rfr_and_comments` "
                    + "FROM    `mot2`.`mot_test_current` AS `mot_test` "
                    + "LEFT JOIN `mot2`.`mot_test_current_rfr_map` AS `rfrmap` ON `rfrmap`.`mot_test_id` = `mot_test`.`id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_location_type` AS `location` ON `location`.`id` = `rfrmap`" +
                    ".`mot_test_rfr_location_type_id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_map_comment` AS `rfrmap_comment` ON `rfrmap_comment`.`id` = `rfrmap`.`id` "
                    + "LEFT JOIN `mot2`.`reason_for_rejection_type` AS `rfr_type` ON `rfr_type`.`id` = `rfrmap`.`rfr_type_id` "
                    + "LEFT JOIN `mot2`.`language_type` AS `l` ON `l`.`code` = 'EN' "
                    + "LEFT JOIN `mot2`.`reason_for_rejection` AS `rfr` ON `rfrmap`.`rfr_id` = `rfr`.`id` "
                    + "LEFT JOIN `mot2`.`rfr_language_content_map` AS `rfrl` ON `rfrl`.`rfr_id` = `rfr`.`id` AND `rfrl`" +
                    ".`language_type_id` = `l`.`id` "
                    + "LEFT JOIN `mot2`.`test_item_category` AS `ti` ON `rfr`.`test_item_category_id` = `ti`.`id` "
                    + "LEFT JOIN `mot2`.`ti_category_language_content_map` AS `timap` ON `timap`.`test_item_category_id` = `rfr`" +
                    ".`test_item_category_id` AND `timap`.`language_lookup_id` = `l`.`id` "
                    + "JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "JOIN "
                    + "( SELECT  `mot_test`.`vehicle_id` "
                    + "  FROM    `mot2`.`mot_test_current` as `mot_test` "
                    + "  JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "  JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "  WHERE   `mot_test`.`submitted_date` >= ? "
                    + "  AND     `mot_test`.`submitted_date` < ? "
                    + "  AND     `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "  AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + ") as `vehicles` on `vehicles`.`vehicle_id` = `mot_test`.`vehicle_id` "
                    + "JOIN    `mot2`.`vehicle` on `vehicle`.`id` = `mot_test`.`vehicle_id` "
                    + "JOIN    `mot2`.`model_detail` on `model_detail`.`id` = `vehicle`.`model_detail_id` "
                    + "JOIN    `mot2`.`model` on `model`.`id` = `model_detail`.`model_id` "
                    + "JOIN    `mot2`.`make` on `make`.`id` = `model`.`make_id` "
                    + "JOIN    `mot2`.`fuel_type` ON `model_detail`.`fuel_type_id` = `fuel_type`.`id` "
                    + "JOIN    `mot2`.`colour_lookup` AS `colour1` ON `colour1`.`id` = `vehicle`.`primary_colour_id` "
                    + "LEFT JOIN `mot2`.`colour_lookup` AS `colour2` ON `colour2`.`id` = `vehicle`.`secondary_colour_id` "
                    + "AND     `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + "ORDER BY `mot_test`.`vehicle_id`, `mot_test`.`id`, `mot_test`.`completed_date` DESC ";

    //Horrible optimised query that breaks the mot_test / vehicle service division
    static final String QueryGetMotHistoryHistoryVehicleByDateRange =
            "SELECT `vehicle`.`id` "
                    + ", `mot_test`.`id` "
                    + ", `rfrmap`.`id` "
                    + ", `vehicle`.`registration` "
                    + ", `make`.`name` AS `make_name` "
                    + ", `model`.`name` AS `model_name` "
                    + ", `vehicle`.`first_used_date` "
                    + ", `fuel_type`.`name` AS `fuel_type` "
                    + ", `colour1`.`name` AS `primary_colour` "
                    + ", `colour2`.`name` AS `secondary_colour` "
                    + ", `mot_test`.`started_date` "
                    + ", `mot_test`.`completed_date` "
                    + ", `mot_test_status`.`name` AS `test_result` "
                    + ", `mot_test`.`expiry_date` "
                    + ", `mot_test`.`odometer_value` "
                    + ", `mot_test`.`odometer_unit` "
                    + ", `mot_test`.`odometer_result_type` "
                    + ", `mot_test`.`number` AS `mot_test_number` "
                    + ", `rfr_type`.`name` `rfr_type` "
                    + ", TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(TRIM(CONCAT(COALESCE(`location`.`lateral`, ''),' ', "
                    + "  COALESCE(`location`.`longitudinal`, ''))), ' ', "
                    + "  COALESCE(`location`.`vertical`, ''))), ' ', "
                    + "  COALESCE(`timap`.`description`, ''))),' ', "
                    + "  CASE WHEN `rfr_type`.`name` = 'ADVISORY' "
                    + "  THEN    COALESCE(`rfrl`.`advisory_text`, '') "
                    + "  ELSE    COALESCE(`rfrl`.`name`, '') "
                    + "  END)),' ',' ', "
                    + "  COALESCE(`rfrmap_comment`.`comment`, ''))), "
                    + "  CASE "
                    + "  WHEN `rfr`.`inspection_manual_reference` IS NOT NULL THEN "
                    + "  CONCAT(' (', `rfr`.`inspection_manual_reference`, ')') ELSE ' ' END)) `rfr_and_comments` "
                    + "FROM    `mot2`.`mot_test_history` AS `mot_test` "
                    + "LEFT JOIN `mot2`.`mot_test_history_rfr_map` AS `rfrmap` ON `rfrmap`.`mot_test_id` = `mot_test`.`id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_location_type` AS `location` ON `location`.`id` = `rfrmap`" +
                    ".`mot_test_rfr_location_type_id` "
                    + "LEFT JOIN `mot2`.`mot_test_rfr_map_comment` AS `rfrmap_comment` ON `rfrmap_comment`.`id` = `rfrmap`.`id` "
                    + "LEFT JOIN `mot2`.`reason_for_rejection_type` AS `rfr_type` ON `rfr_type`.`id` = `rfrmap`.`rfr_type_id` "
                    + "LEFT JOIN `mot2`.`language_type` AS `l` ON `l`.`code` = 'EN' "
                    + "LEFT JOIN `mot2`.`reason_for_rejection` AS `rfr` ON `rfrmap`.`rfr_id` = `rfr`.`id` "
                    + "LEFT JOIN `mot2`.`rfr_language_content_map` AS `rfrl` ON `rfrl`.`rfr_id` = `rfr`.`id` AND `rfrl`" +
                    ".`language_type_id` = `l`.`id` "
                    + "LEFT JOIN `mot2`.`test_item_category` AS `ti` ON `rfr`.`test_item_category_id` = `ti`.`id` "
                    + "LEFT JOIN `mot2`.`ti_category_language_content_map` AS `timap` ON `timap`.`test_item_category_id` = `rfr`" +
                    ".`test_item_category_id` AND `timap`.`language_lookup_id` = `l`.`id` "
                    + "JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "JOIN "
                    + "( SELECT  `mot_test`.`vehicle_id` "
                    + "  FROM    `mot2`.`mot_test_current` as `mot_test` "
                    + "  JOIN    `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test`.`mot_test_type_id` "
                    + "  JOIN    `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test`.`status_id` "
                    + "  WHERE   `mot_test`.`submitted_date` >= ? "
                    + "  AND     `mot_test`.`submitted_date` < ? "
                    + "  AND     `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "  AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + ") as `vehicles` on `vehicles`.`vehicle_id` = `mot_test`.`vehicle_id` "
                    + "JOIN    `mot2`.`vehicle` on `vehicle`.`id` = `mot_test`.`vehicle_id` "
                    + "JOIN    `mot2`.`model_detail` on `model_detail`.`id` = `vehicle`.`model_detail_id` "
                    + "JOIN    `mot2`.`model` on `model`.`id` = `model_detail`.`model_id` "
                    + "JOIN    `mot2`.`make` on `make`.`id` = `model`.`make_id` "
                    + "JOIN    `mot2`.`fuel_type` ON `model_detail`.`fuel_type_id` = `fuel_type`.`id` "
                    + "JOIN    `mot2`.`colour_lookup` AS `colour1` ON `colour1`.`id` = `vehicle`.`primary_colour_id` "
                    + "LEFT JOIN `mot2`.`colour_lookup` AS `colour2` ON `colour2`.`id` = `vehicle`.`secondary_colour_id` "
                    + "AND     `mot_test_type`.`code` IN ('NT','PL', 'PV', 'RT') "
                    + "AND     `mot_test_status`.`code` IN ('P' , 'F') "
                    + "ORDER BY `mot_test`.`vehicle_id`, `mot_test`.`id`, `mot_test`.`completed_date` DESC ";

    static final String queryGetMotTestCurrentById = "SELECT `mot_test_current`.`id` "
            + ", `mot_test_current`.`person_id` " + ", `mot_test_current`.`vehicle_id` "
            + ", `mot_test_current`.`vehicle_version` " + ", `mot_test_current`.`document_id` "
            + ", `mot_test_current`.`organisation_id` " + ", `mot_test_current`.`site_id` "
            + ", `mot_test_current`.`has_registration` " + ", `mot_test_current`.`mot_test_type_id` "
            + ", `mot_test_current`.`started_date` " + ", `mot_test_current`.`completed_date` "
            + ", `mot_test_current`.`submitted_date` " + ", `mot_test_current`.`status_id` "
            + ", `mot_test_current`.`issued_date` " + ", `mot_test_current`.`expiry_date` "
            + ", `mot_test_current`.`mot_test_id_original` " + ", `mot_test_current`.`prs_mot_test_id` "
            + ", `mot_test_current`.`number` " + ", `mot_test_current`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_current`.`vehicle_weight` " + ", `mot_test_current`.`odometer_value` "
            + ", `mot_test_current`.`odometer_unit` " + ", `mot_test_current`.`odometer_result_type` "
            + ", `mot_test_current`.`created_by` " + ", `mot_test_current`.`created_on` "
            + ", `mot_test_current`.`last_updated_by` " + ", `mot_test_current`.`last_updated_on` "
            + ", `mot_test_current`.`version` " + ", `mot_test_current`.`client_ip` " + "FROM  `mot2`.`mot_test_current` "
            + "WHERE `mot_test_current`.`id` = ?";

    static final String queryGetMotTestHistoryById = "SELECT `mot_test_history`.`id` "
            + ", `mot_test_history`.`person_id` " + ", `mot_test_history`.`vehicle_id` "
            + ", `mot_test_history`.`vehicle_version` " + ", `mot_test_history`.`document_id` "
            + ", `mot_test_history`.`organisation_id` " + ", `mot_test_history`.`site_id` "
            + ", `mot_test_history`.`has_registration` " + ", `mot_test_history`.`mot_test_type_id` "
            + ", `mot_test_history`.`started_date` " + ", `mot_test_history`.`completed_date` "
            + ", `mot_test_history`.`submitted_date` " + ", `mot_test_history`.`status_id` "
            + ", `mot_test_history`.`issued_date` " + ", `mot_test_history`.`expiry_date` "
            + ", `mot_test_history`.`mot_test_id_original` " + ", `mot_test_history`.`prs_mot_test_id` "
            + ", `mot_test_history`.`number` " + ", `mot_test_history`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_history`.`vehicle_weight` " + ", `mot_test_history`.`odometer_value` "
            + ", `mot_test_history`.`odometer_unit` " + ", `mot_test_history`.`odometer_result_type` "
            + ", `mot_test_history`.`created_by` " + ", `mot_test_history`.`created_on` "
            + ", `mot_test_history`.`last_updated_by` " + ", `mot_test_history`.`last_updated_on` "
            + ", `mot_test_history`.`version` " + ", `mot_test_history`.`client_ip` " + "FROM  `mot2`.`mot_test_history` "
            + "WHERE `mot_test_history`.`id` = ?";

    static final String queryGetMotTestCurrentByNumber = "SELECT `mot_test_current`.`id` "
            + ", `mot_test_current`.`person_id` " + ", `mot_test_current`.`vehicle_id` "
            + ", `mot_test_current`.`vehicle_version` " + ", `mot_test_current`.`document_id` "
            + ", `mot_test_current`.`organisation_id` " + ", `mot_test_current`.`site_id` "
            + ", `mot_test_current`.`has_registration` " + ", `mot_test_current`.`mot_test_type_id` "
            + ", `mot_test_current`.`started_date` " + ", `mot_test_current`.`completed_date` "
            + ", `mot_test_current`.`submitted_date` " + ", `mot_test_current`.`status_id` "
            + ", `mot_test_current`.`issued_date` " + ", `mot_test_current`.`expiry_date` "
            + ", `mot_test_current`.`mot_test_id_original` " + ", `mot_test_current`.`prs_mot_test_id` "
            + ", `mot_test_current`.`number` " + ", `mot_test_current`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_current`.`vehicle_weight` " + ", `mot_test_current`.`odometer_value` "
            + ", `mot_test_current`.`odometer_unit` " + ", `mot_test_current`.`odometer_result_type` "
            + ", `mot_test_current`.`created_by` " + ", `mot_test_current`.`created_on` "
            + ", `mot_test_current`.`last_updated_by` " + ", `mot_test_current`.`last_updated_on` "
            + ", `mot_test_current`.`version` " + ", `mot_test_current`.`client_ip` " + "FROM  `mot2`.`mot_test_current` "
            + "WHERE `mot_test_current`.`number` = ?";

    static final String queryGetMotTestHistoryByNumber = "SELECT `mot_test_history`.`id` "
            + ", `mot_test_history`.`person_id` " + ", `mot_test_history`.`vehicle_id` "
            + ", `mot_test_history`.`vehicle_version` " + ", `mot_test_history`.`document_id` "
            + ", `mot_test_history`.`organisation_id` " + ", `mot_test_history`.`site_id` "
            + ", `mot_test_history`.`has_registration` " + ", `mot_test_history`.`mot_test_type_id` "
            + ", `mot_test_history`.`started_date` " + ", `mot_test_history`.`completed_date` "
            + ", `mot_test_history`.`submitted_date` " + ", `mot_test_history`.`status_id` "
            + ", `mot_test_history`.`issued_date` " + ", `mot_test_history`.`expiry_date` "
            + ", `mot_test_history`.`mot_test_id_original` " + ", `mot_test_history`.`prs_mot_test_id` "
            + ", `mot_test_history`.`number` " + ", `mot_test_history`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_history`.`vehicle_weight` " + ", `mot_test_history`.`odometer_value` "
            + ", `mot_test_history`.`odometer_unit` " + ", `mot_test_history`.`odometer_result_type` "
            + ", `mot_test_history`.`created_by` " + ", `mot_test_history`.`created_on` "
            + ", `mot_test_history`.`last_updated_by` " + ", `mot_test_history`.`last_updated_on` "
            + ", `mot_test_history`.`version` " + ", `mot_test_history`.`client_ip` " + "FROM  `mot2`.`mot_test_history` "
            + "WHERE `mot_test_history`.`number` = ?";

    static final String queryGetReasonForRejectionById = "SELECT `reason_for_rejection`.`id` "
            + ", `reason_for_rejection`.`test_item_category_id` " + ", `reason_for_rejection`.`test_item_selector_name` "
            + ", `reason_for_rejection`.`test_item_selector_name_cy` "
            + ", `reason_for_rejection`.`inspection_manual_reference` " + ", `reason_for_rejection`.`minor_item` "
            + ", `reason_for_rejection`.`location_marker` " + ", `reason_for_rejection`.`qt_marker` "
            + ", `reason_for_rejection`.`note` " + ", `reason_for_rejection`.`manual` "
            + ", `reason_for_rejection`.`spec_proc` " + ", `reason_for_rejection`.`is_advisory` "
            + ", `reason_for_rejection`.`is_prs_fail` " + ", `reason_for_rejection`.`section_test_item_selector_id` "
            + ", `reason_for_rejection`.`can_be_dangerous` " + ", `reason_for_rejection`.`date_first_used` "
            + ", `reason_for_rejection`.`audience` " + ", `reason_for_rejection`.`end_date` "
            + ", `reason_for_rejection`.`created_by` " + ", `reason_for_rejection`.`created_on` "
            + ", `reason_for_rejection`.`last_updated_by` " + ", `reason_for_rejection`.`last_updated_on` "
            + ", `reason_for_rejection`.`version` " + "FROM `mot2`.`reason_for_rejection` "
            + "WHERE `reason_for_rejection`.`id` = ?";

    static final String queryGetReasonForRejectionTypeById = "SELECT `reason_for_rejection_type`.`id` "
            + ", `reason_for_rejection_type`.`name` " + ", `reason_for_rejection_type`.`code` "
            + ", `reason_for_rejection_type`.`description` " + ", `reason_for_rejection_type`.`created_by` "
            + ", `reason_for_rejection_type`.`created_on` " + ", `reason_for_rejection_type`.`last_updated_by` "
            + ", `reason_for_rejection_type`.`last_updated_on` " + ", `reason_for_rejection_type`.`version` "
            + "FROM `mot2`.`reason_for_rejection_type` " + "WHERE `reason_for_rejection_type`.`id` = ?";

    static final String queryGetMotTestRfrLocationTypeById = "SELECT `mot_test_rfr_location_type`.`id` "
            + ", `mot_test_rfr_location_type`.`lateral` " + ", `mot_test_rfr_location_type`.`longitudinal` "
            + ", `mot_test_rfr_location_type`.`vertical` " + ", `mot_test_rfr_location_type`.`created_by` "
            + ", `mot_test_rfr_location_type`.`created_on` " + ", `mot_test_rfr_location_type`.`last_updated_by` "
            + ", `mot_test_rfr_location_type`.`last_updated_on` " + ", `mot_test_rfr_location_type`.`version` "
            + ", `mot_test_rfr_location_type`.`sha1_concat_ws_chksum` " + "FROM `mot2`.`mot_test_rfr_location_type` "
            + "WHERE `mot_test_rfr_location_type`.`id` = ?";

    static final String queryGetRfrLanguageContentMapByReasonForRejection = "SELECT `rfr_language_content_map`.`id` "
            + ", `rfr_language_content_map`.`rfr_id` " + ", `rfr_language_content_map`.`language_type_id` "
            + ", `rfr_language_content_map`.`name` " + ", `rfr_language_content_map`.`inspection_manual_description` "
            + ", `rfr_language_content_map`.`advisory_text` " + ", `rfr_language_content_map`.`test_item_selector_name` "
            + ", `rfr_language_content_map`.`created_by` " + ", `rfr_language_content_map`.`created_on` "
            + ", `rfr_language_content_map`.`last_updated_by` " + ", `rfr_language_content_map`.`last_updated_on` "
            + ", `rfr_language_content_map`.`version` " + "FROM `mot2`.`rfr_language_content_map` "
            + "WHERE `rfr_language_content_map`.`rfr_id` = ?";

    static final String queryGetTestItemCategoryById = "SELECT `test_item_category`.`id` "
            + ", `test_item_category`.`parent_test_item_category_id` "
            + ", `test_item_category`.`section_test_item_category_id` " + ", `test_item_category`.`business_rule_id` "
            + ", `test_item_category`.`created_by` " + ", `test_item_category`.`created_on` "
            + ", `test_item_category`.`last_updated_by` " + ", `test_item_category`.`last_updated_on` "
            + ", `test_item_category`.`version` " + "FROM `mot2`.`test_item_category` "
            + "WHERE `test_item_category`.`id` = ?";

    static final String queryGetTiCategoryLanguageContentMapByTestItemCategory = "SELECT `ti_category_language_content_map`.`id` "
            + ", `ti_category_language_content_map`.`test_item_category_id` "
            + ", `ti_category_language_content_map`.`language_lookup_id` " + ", `ti_category_language_content_map`.`name` "
            + ", `ti_category_language_content_map`.`description` " + ", `ti_category_language_content_map`.`display_order` "
            + ", `ti_category_language_content_map`.`created_by` " + ", `ti_category_language_content_map`.`created_on` "
            + ", `ti_category_language_content_map`.`last_updated_by` "
            + ", `ti_category_language_content_map`.`last_updated_on` " + ", `ti_category_language_content_map`.`version` "
            + "FROM `mot2`.`ti_category_language_content_map` "
            + "WHERE `ti_category_language_content_map`.`test_item_category_id` = ?";

    static final String queryGetLanguageTypeById = "SELECT `language_type`.`id` " + ", `language_type`.`name` "
            + ", `language_type`.`code` " + ", `language_type`.`created_by` " + ", `language_type`.`created_on` "
            + ", `language_type`.`last_updated_by` " + ", `language_type`.`last_updated_on` " + ", `language_type`.`version` "
            + "FROM `mot2`.`language_type` " + "WHERE `language_type`.`id` = ?";

    static final String queryGetBusinessRuleById = "SELECT `business_rule`.`id` " + ", `business_rule`.`name` "
            + ", `business_rule`.`definition` " + ", `business_rule`.`business_rule_type_id` "
            + ", `business_rule`.`comparison` " + ", `business_rule`.`date_value` " + ", `business_rule`.`created_by` "
            + ", `business_rule`.`created_on` " + ", `business_rule`.`last_updated_by` "
            + ", `business_rule`.`last_updated_on` " + ", `business_rule`.`version` " + "FROM `mot2`.`business_rule` "
            + "WHERE `business_rule`.`id` = ?";

    static final String queryGetBusinessRuleTypeById = "SELECT `business_rule_type`.`id` "
            + ", `business_rule_type`.`name` " + ", `business_rule_type`.`code` " + ", `business_rule_type`.`created_by` "
            + ", `business_rule_type`.`created_on` " + ", `business_rule_type`.`last_updated_by` "
            + ", `business_rule_type`.`last_updated_on` " + ", `business_rule_type`.`version` "
            + "FROM `mot2`.`business_rule_type` " + "WHERE `business_rule_type`.`id` = ?";

    static final String queryGetPersonById = "SELECT `person`.`id` " + ", `person`.`username` " + ", `person`.`pin` "
            + ", `person`.`person_auth_type_lookup_id` " + ", `person`.`user_reference` " + ", `person`.`mot_one_user_id` "
            + ", `person`.`title_id` " + ", `person`.`first_name` " + ", `person`.`middle_name` "
            + ", `person`.`family_name` " + ", `person`.`driving_licence_id` " + ", `person`.`gender_id` "
            + ", `person`.`date_of_birth` " + ", `person`.`disability` " + ", `person`.`demo_test_tester_status_id` "
            + ", `person`.`otp_failed_attempts` " + ", `person`.`is_account_claim_required` "
            + ", `person`.`is_password_change_required` " + ", `person`.`transition_status_id` " + ", `person`.`mot1_userid` "
            + ", `person`.`mot1_current_smartcard_id` " + ", `person`.`2fa_token_id` " + ", `person`.`2fa_token_sent_on` "
            + ", `person`.`details_confirmed_on` " + ", `person`.`first_training_test_done_on` "
            + ", `person`.`first_live_test_done_on` " + ", `person`.`is_deceased` " + ", `person`.`deceased_on` "
            + ", `person`.`mot1_details_updated_on` " + ", `person`.`created_by` " + ", `person`.`created_on` "
            + ", `person`.`last_updated_by` " + ", `person`.`last_updated_on` " + ", `person`.`version` "
            + "FROM `mot2`.`person` " + "WHERE `person`.`id` = ?";

    static final String queryGetMotTestCurrentRfrMapsByMotTestId = "SELECT `mot_test_current_rfr_map`.`id` "
            // + ", `mot_test_current_rfr_map`.`mot_test_id` "
            + ", `mot_test_current_rfr_map`.`rfr_id` " + ", `mot_test_current_rfr_map`.`rfr_type_id` "
            + ", `mot_test_current_rfr_map`.`mot_test_rfr_location_type_id` "
            + ", `mot_test_current_rfr_map`.`failure_dangerous` " + ", `mot_test_current_rfr_map`.`generated` "
            + ", `mot_test_current_rfr_map`.`on_original_test` " + ", `mot_test_current_rfr_map`.`created_by` "
            + ", `mot_test_current_rfr_map`.`created_on` " + ", `mot_test_current_rfr_map`.`last_updated_by` "
            + ", `mot_test_current_rfr_map`.`last_updated_on` " + ", `mot_test_current_rfr_map`.`version` "
            + "FROM `mot2`.`mot_test_current_rfr_map` " + "WHERE `mot_test_current_rfr_map`.`mot_test_id` = ?";

    static final String queryGetMotTestHistoryRfrMapsByMotTestId = "SELECT `mot_test_history_rfr_map`.`id` "
            // + ", `mot_test_history_rfr_map`.`mot_test_id` "
            + ", `mot_test_history_rfr_map`.`rfr_id` " + ", `mot_test_history_rfr_map`.`rfr_type_id` "
            + ", `mot_test_history_rfr_map`.`mot_test_rfr_location_type_id` "
            + ", `mot_test_history_rfr_map`.`failure_dangerous` " + ", `mot_test_history_rfr_map`.`generated` "
            + ", `mot_test_history_rfr_map`.`on_original_test` " + ", `mot_test_history_rfr_map`.`created_by` "
            + ", `mot_test_history_rfr_map`.`created_on` " + ", `mot_test_history_rfr_map`.`last_updated_by` "
            + ", `mot_test_history_rfr_map`.`last_updated_on` " + ", `mot_test_history_rfr_map`.`version` "
            + "FROM `mot2`.`mot_test_history_rfr_map` " + "WHERE `mot_test_history_rfr_map`.`mot_test_id` = ?";

    static final String queryGetMotTestAddressCommentByMotTestId = "SELECT `mot_test_address_comment`.`id` "
            // + ", `mot_test_address_comment`.`mot_test_id` "
            + ", `mot_test_address_comment`.`address_comment_id` " + ", `mot_test_address_comment`.`created_by` "
            + ", `mot_test_address_comment`.`created_on` " + ", `mot_test_address_comment`.`last_updated_by` "
            + ", `mot_test_address_comment`.`last_updated_on` " + ", `mot_test_address_comment`.`version` "
            + "FROM `mot2`.`mot_test_address_comment` " + "WHERE `mot_test_address_comment`.`id` = ?";

    static final String queryGetMotTestCancelledByMotTestId = "SELECT `mot_test_cancelled`.`id` "
            // + ", `mot_test_cancelled`.`mot_test_id` "
            + ", `mot_test_cancelled`.`mot_test_reason_for_cancel_id` "
            + ", `mot_test_cancelled`.`reason_for_cancel_comment_id` " + ", `mot_test_cancelled`.`created_by` "
            + ", `mot_test_cancelled`.`created_on` " + ", `mot_test_cancelled`.`last_updated_by` "
            + ", `mot_test_cancelled`.`last_updated_on` " + ", `mot_test_cancelled`.`version` "
            + "FROM `mot2`.`mot_test_cancelled` " + "WHERE `mot_test_cancelled`.`id` = ?";

    static final String queryGetMotTestComplaintRefByMotTestId = "SELECT `mot_test_complaint_ref`.`id` "
            // + ", `mot_test_complaint_ref`.`mot_test_id` "
            + ", `mot_test_complaint_ref`.`complaint_ref` " + ", `mot_test_complaint_ref`.`created_by` "
            + ", `mot_test_complaint_ref`.`created_on` " + ", `mot_test_complaint_ref`.`last_updated_by` "
            + ", `mot_test_complaint_ref`.`last_updated_on` " + ", `mot_test_complaint_ref`.`version` "
            + "FROM `mot2`.`mot_test_complaint_ref` " + "WHERE `mot_test_complaint_ref`.`id` = ?";

    static final String queryGetMotTestEmergencyReasonByMotTestId = "SELECT `mot_test_emergency_reason`.`id` "
            // + ", `mot_test_emergency_reason`.`mot_test_id` "
            + ", `mot_test_emergency_reason`.`emergency_log_id` "
            + ", `mot_test_emergency_reason`.`emergency_reason_lookup_id` "
            + ", `mot_test_emergency_reason`.`emergency_reason_comment_id` " + ", `mot_test_emergency_reason`.`created_by` "
            + ", `mot_test_emergency_reason`.`created_on` " + ", `mot_test_emergency_reason`.`last_updated_by` "
            + ", `mot_test_emergency_reason`.`last_updated_on` " + ", `mot_test_emergency_reason`.`version` "
            + "FROM `mot2`.`mot_test_emergency_reason` " + "WHERE `mot_test_emergency_reason`.`id` = ?";

    static final String queryGetCommentById = "SELECT `comment`.`id` " + ", `comment`.`comment` "
            + ", `comment`.`author_person_id` " + ", `comment`.`created_by` " + ", `comment`.`created_on` "
            + ", `comment`.`last_updated_by` " + ", `comment`.`last_updated_on` " + ", `comment`.`version` "
            + "FROM `mot2`.`comment` " + "WHERE `comment`.`id` = ?";

    static final String queryGetMotTestReasonForCancelLookupById = "SELECT `mot_test_reason_for_cancel_lookup`.`id` "
            + ", `mot_test_reason_for_cancel_lookup`.`code` " + ", `mot_test_reason_for_cancel_lookup`.`reason` "
            + ", `mot_test_reason_for_cancel_lookup`.`reason_cy` "
            + ", `mot_test_reason_for_cancel_lookup`.`is_system_generated` "
            + ", `mot_test_reason_for_cancel_lookup`.`is_displayable` "
            + ", `mot_test_reason_for_cancel_lookup`.`is_abandoned` " + ", `mot_test_reason_for_cancel_lookup`.`created_by` "
            + ", `mot_test_reason_for_cancel_lookup`.`created_on` "
            + ", `mot_test_reason_for_cancel_lookup`.`last_updated_by` "
            + ", `mot_test_reason_for_cancel_lookup`.`last_updated_on` " + ", `mot_test_reason_for_cancel_lookup`.`version` "
            + "FROM `mot2`.`mot_test_reason_for_cancel_lookup` " + "WHERE `mot_test_reason_for_cancel_lookup`.`id` = ?";

    static final String queryGetEmergencyLogById = "SELECT `emergency_log`.`id` " + ", `emergency_log`.`number` "
            + ", `emergency_log`.`description` " + ", `emergency_log`.`start_date` " + ", `emergency_log`.`end_date` "
            + ", `emergency_log`.`created_by` " + ", `emergency_log`.`created_on` " + ", `emergency_log`.`last_updated_by` "
            + ", `emergency_log`.`last_updated_on` " + ", `emergency_log`.`version` " + "FROM `mot2`.`emergency_log` "
            + "WHERE `emergency_log`.`id` = ?";

    static final String queryGetEmergencyReasonLookupById = "SELECT `emergency_reason_lookup`.`id` "
            + ", `emergency_reason_lookup`.`name` " + ", `emergency_reason_lookup`.`code` "
            + ", `emergency_reason_lookup`.`description` " + ", `emergency_reason_lookup`.`display_order` "
            + ", `emergency_reason_lookup`.`created_by` " + ", `emergency_reason_lookup`.`created_on` "
            + ", `emergency_reason_lookup`.`last_updated_by` " + ", `emergency_reason_lookup`.`last_updated_on` "
            + ", `emergency_reason_lookup`.`version` " + "FROM `mot2`.`emergency_reason_lookup` "
            + "WHERE `emergency_reason_lookup`.`id` = ?";

    static final String queryGetMotTestRfrMapCommentByMotTestRfrMapId = "SELECT `mot_test_rfr_map_comment`.`id` "
            // + ", `mot_test_rfr_map_comment`.`mot_test_rfr_map_id` "
            + ", `mot_test_rfr_map_comment`.`comment` " + ", `mot_test_rfr_map_comment`.`created_by` "
            + ", `mot_test_rfr_map_comment`.`created_on` " + ", `mot_test_rfr_map_comment`.`last_updated_by` "
            + ", `mot_test_rfr_map_comment`.`last_updated_on` " + ", `mot_test_rfr_map_comment`.`version` "
            + "FROM `mot2`.`mot_test_rfr_map_comment` " + "WHERE `mot_test_rfr_map_comment`.`id` = ?";

    static final String queryGetMotTestRfrMapCustomDescriptionByMotTestRfrMapId = "SELECT `mot_test_rfr_map_custom_description`.`id` "
            // + ", `mot_test_rfr_map_custom_description`.`mot_test_rfr_map_id` "
            + ", `mot_test_rfr_map_custom_description`.`custom_description` "
            + ", `mot_test_rfr_map_custom_description`.`created_by` "
            + ", `mot_test_rfr_map_custom_description`.`created_on` "
            + ", `mot_test_rfr_map_custom_description`.`last_updated_by` "
            + ", `mot_test_rfr_map_custom_description`.`last_updated_on` "
            + ", `mot_test_rfr_map_custom_description`.`version` " + "FROM `mot2`.`mot_test_rfr_map_custom_description` "
            + "WHERE `mot_test_rfr_map_custom_description`.`id` = ?";

    static final String queryGetOrganisationById = "SELECT `organisation`.`id` " + "FROM `mot2`.`organisation` "
            + "WHERE `organisation`.`id` = ?";

    static final String queryGetSiteById = "SELECT `site`.`id` " + "FROM `mot2`.`site` " + "WHERE `site`.`id` = ?";

    static final String queryGetJasperDocumentById = "SELECT `jasper_document`.`id` " + "FROM `mot2`.`jasper_document` "
            + "WHERE `jasper_document`.`id` = ?";

    static final String queryGetMotTestTypeById = "SELECT `mot_test_type`.`id` " + ", `mot_test_type`.`code` "
            + ", `mot_test_type`.`description` " + ", `mot_test_type`.`display_order` " + ", `mot_test_type`.`is_demo` "
            + ", `mot_test_type`.`is_reinspection` " + ", `mot_test_type`.`is_slot_consuming` "
            + ", `mot_test_type`.`created_by` " + ", `mot_test_type`.`created_on` " + ", `mot_test_type`.`last_updated_by` "
            + ", `mot_test_type`.`last_updated_on` " + ", `mot_test_type`.`version` " + "FROM `mot2`.`mot_test_type` "
            + "WHERE `mot_test_type`.`id` = ?";

    static final String queryGetMotTestStatusById = "SELECT `mot_test_status`.`id` " + ", `mot_test_status`.`code` "
            + ", `mot_test_status`.`name` " + ", `mot_test_status`.`description` " + ", `mot_test_status`.`created_by` "
            + ", `mot_test_status`.`created_on` " + ", `mot_test_status`.`last_updated_by` "
            + ", `mot_test_status`.`last_updated_on` " + ", `mot_test_status`.`version` " + "FROM `mot2`.`mot_test_status` "
            + "WHERE `mot_test_status`.`id` = ?";

    static final String queryGetMotTestCurrentsByDateRange = "SELECT `mot_test_current`.`id` "
            + ", `mot_test_current`.`person_id` " + ", `mot_test_current`.`vehicle_id` "
            + ", `mot_test_current`.`vehicle_version` " + ", `mot_test_current`.`document_id` "
            + ", `mot_test_current`.`organisation_id` " + ", `mot_test_current`.`site_id` "
            + ", `mot_test_current`.`has_registration` " + ", `mot_test_current`.`mot_test_type_id` "
            + ", `mot_test_current`.`started_date` " + ", `mot_test_current`.`completed_date` "
            + ", `mot_test_current`.`submitted_date` " + ", `mot_test_current`.`status_id` "
            + ", `mot_test_current`.`issued_date` " + ", `mot_test_current`.`expiry_date` "
            + ", `mot_test_current`.`mot_test_id_original` " + ", `mot_test_current`.`prs_mot_test_id` "
            + ", `mot_test_current`.`number` " + ", `mot_test_current`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_current`.`vehicle_weight` " + ", `mot_test_current`.`odometer_value` "
            + ", `mot_test_current`.`odometer_unit` " + ", `mot_test_current`.`odometer_result_type` "
            + ", `mot_test_current`.`created_by` " + ", `mot_test_current`.`created_on` "
            + ", `mot_test_current`.`last_updated_by` " + ", `mot_test_current`.`last_updated_on` "
            + ", `mot_test_current`.`version` " + ", `mot_test_current`.`client_ip` " + "FROM  `mot2`.`mot_test_current` "
            + "JOIN  `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test_current`.`mot_test_type_id` "
            + "JOIN  `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test_current`.`status_id` "
            + "WHERE `mot_test_current`.`submitted_date` >= ? " + "AND   `mot_test_current`.`submitted_date` < ? "
            + "AND   `mot_test_type`.`code` IN ( 'NT', 'PL', 'PV', 'RT' ) "
            + "AND   `mot_test_status`.`code` IN ( 'P', 'F' ) "
            + "ORDER BY `mot_test_current`.`completed_date` desc, `mot_test_current`.`id` desc ";

    static final String queryGetMotTestHistorysByDateRange = "SELECT `mot_test_history`.`id` "
            + ", `mot_test_history`.`person_id` " + ", `mot_test_history`.`vehicle_id` "
            + ", `mot_test_history`.`vehicle_version` " + ", `mot_test_history`.`document_id` "
            + ", `mot_test_history`.`organisation_id` " + ", `mot_test_history`.`site_id` "
            + ", `mot_test_history`.`has_registration` " + ", `mot_test_history`.`mot_test_type_id` "
            + ", `mot_test_history`.`started_date` " + ", `mot_test_history`.`completed_date` "
            + ", `mot_test_history`.`submitted_date` " + ", `mot_test_history`.`status_id` "
            + ", `mot_test_history`.`issued_date` " + ", `mot_test_history`.`expiry_date` "
            + ", `mot_test_history`.`mot_test_id_original` " + ", `mot_test_history`.`prs_mot_test_id` "
            + ", `mot_test_history`.`number` " + ", `mot_test_history`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_history`.`vehicle_weight` " + ", `mot_test_history`.`odometer_value` "
            + ", `mot_test_history`.`odometer_unit` " + ", `mot_test_history`.`odometer_result_type` "
            + ", `mot_test_history`.`created_by` " + ", `mot_test_history`.`created_on` "
            + ", `mot_test_history`.`last_updated_by` " + ", `mot_test_history`.`last_updated_on` "
            + ", `mot_test_history`.`version` " + ", `mot_test_history`.`client_ip` " + "FROM  `mot2`.`mot_test_history` "
            + "JOIN  `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test_history`.`mot_test_type_id` "
            + "JOIN  `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test_history`.`status_id` "
            + "WHERE `mot_test_history`.`submitted_date` >= ? " + "AND   `mot_test_history`.`submitted_date` < ? "
            + "AND   `mot_test_type`.`code` IN ( 'NT', 'PL', 'PV', 'RT' ) "
            + "AND   `mot_test_status`.`code` IN ( 'P', 'F' ) "
            + "ORDER BY `mot_test_history`.`completed_date` desc, `mot_test_history`.`id` desc ";

    static final String queryGetMotTestCurrentsByIdRange = "SELECT `mot_test_current`.`id` "
            + ", `mot_test_current`.`person_id` " + ", `mot_test_current`.`vehicle_id` "
            + ", `mot_test_current`.`vehicle_version` " + ", `mot_test_current`.`document_id` "
            + ", `mot_test_current`.`organisation_id` " + ", `mot_test_current`.`site_id` "
            + ", `mot_test_current`.`has_registration` " + ", `mot_test_current`.`mot_test_type_id` "
            + ", `mot_test_current`.`started_date` " + ", `mot_test_current`.`completed_date` "
            + ", `mot_test_current`.`submitted_date` " + ", `mot_test_current`.`status_id` "
            + ", `mot_test_current`.`issued_date` " + ", `mot_test_current`.`expiry_date` "
            + ", `mot_test_current`.`mot_test_id_original` " + ", `mot_test_current`.`prs_mot_test_id` "
            + ", `mot_test_current`.`number` " + ", `mot_test_current`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_current`.`vehicle_weight` " + ", `mot_test_current`.`odometer_value` "
            + ", `mot_test_current`.`odometer_unit` " + ", `mot_test_current`.`odometer_result_type` "
            + ", `mot_test_current`.`created_by` " + ", `mot_test_current`.`created_on` "
            + ", `mot_test_current`.`last_updated_by` " + ", `mot_test_current`.`last_updated_on` "
            + ", `mot_test_current`.`version` " + ", `mot_test_current`.`client_ip` " + "FROM  `mot2`.`mot_test_current` "
            + "JOIN  `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test_current`.`mot_test_type_id` "
            + "JOIN  `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test_current`.`status_id` "
            + "WHERE `mot_test_current`.`id` >= ? " + "AND   `mot_test_current`.`id` < ? "
            + "AND   `mot_test_type`.`code` IN ( 'NT', 'PL', 'PV', 'RT' ) "
            + "AND   `mot_test_status`.`code` IN ( 'P', 'F' ) "
            + "ORDER BY `mot_test_current`.`completed_date` desc, `mot_test_current`.`id` desc ";

    static final String queryGetMotTestHistorysByIdRange = "SELECT `mot_test_history`.`id` "
            + ", `mot_test_history`.`person_id` " + ", `mot_test_history`.`vehicle_id` "
            + ", `mot_test_history`.`vehicle_version` " + ", `mot_test_history`.`document_id` "
            + ", `mot_test_history`.`organisation_id` " + ", `mot_test_history`.`site_id` "
            + ", `mot_test_history`.`has_registration` " + ", `mot_test_history`.`mot_test_type_id` "
            + ", `mot_test_history`.`started_date` " + ", `mot_test_history`.`completed_date` "
            + ", `mot_test_history`.`submitted_date` " + ", `mot_test_history`.`status_id` "
            + ", `mot_test_history`.`issued_date` " + ", `mot_test_history`.`expiry_date` "
            + ", `mot_test_history`.`mot_test_id_original` " + ", `mot_test_history`.`prs_mot_test_id` "
            + ", `mot_test_history`.`number` " + ", `mot_test_history`.`vehicle_weight_source_lookup_id` "
            + ", `mot_test_history`.`vehicle_weight` " + ", `mot_test_history`.`odometer_value` "
            + ", `mot_test_history`.`odometer_unit` " + ", `mot_test_history`.`odometer_result_type` "
            + ", `mot_test_history`.`created_by` " + ", `mot_test_history`.`created_on` "
            + ", `mot_test_history`.`last_updated_by` " + ", `mot_test_history`.`last_updated_on` "
            + ", `mot_test_history`.`version` " + ", `mot_test_history`.`client_ip` " + "FROM  `mot2`.`mot_test_history` "
            + "JOIN  `mot2`.`mot_test_type` on `mot_test_type`.`id` = `mot_test_history`.`mot_test_type_id` "
            + "JOIN  `mot2`.`mot_test_status` on `mot_test_status`.`id` = `mot_test_history`.`status_id` "
            + "WHERE `mot_test_history`.`id` >= ? " + "AND   `mot_test_history`.`id` < ? "
            + "AND   `mot_test_type`.`code` IN ( 'NT', 'PL', 'PV', 'RT' ) "
            + "AND   `mot_test_status`.`code` IN ( 'P', 'F' ) "
            + "ORDER BY `mot_test_history`.`completed_date` desc, `mot_test_history`.`id` desc ";
}
